# madlibs fantasy game made by Josh that includes filipinos and dragons :)

def madlibs():
    print("Hello! Welcome to Josh's Madlibs Adventure! Let's create a wild Filipino fantasy story together :>")
    print("I'll ask you for some words, then your journey will begin! \n")
    
    # input the variables
    print("First, give me some words:")
    
    storeName = input("Enter a name for the sari-sari store owner: ")
    thingOne = input("Enter an item sold in a sari-sari store (e.g., 'pancit canton', 'fishball'): ")
    thingTwo = input("Enter another sari-sari store item: ")
    adjOne = input("Enter an adjective (describing word, e.g., 'makulit', 'sparkling'): ")
    soundEffect = input("Enter a sound (e.g., 'boom', 'kaboom', 'whoosh'): ")
    adjTwo = input("Enter another adjective: ")
    faveFood = input("Enter your favorite Filipino food: ")
    feeling = input("Enter an emotion (e.g., 'takot', 'excited', 'confused'): ")
    location = input("Enter a place in the Philippines (e.g., 'Palawan', 'Baguio', 'Boracay'): ")
    num = input("Enter a number: ")
    bodyPart = input("Enter a body part (e.g., 'tenga', 'paa', 'ilong'): ")
    exclaim = input("Enter an exclamation (e.g., 'Ay sus!', 'Hala!', 'Naku!'): ")
    creature = input("Enter a mythical creature (e.g., 'kapre', 'tikbalang', 'diwata'): ")
    
    # story/storyline starts here
    print("\n" + "=" * 60)
    print("THE LEGEND OF THE SARI-SARI STORE DRAGON")
    print("=" * 60 + "\n")
    
    # the storyline
    print(f"It was just another ordinary day at Aling {storeName}'s sari-sari store in the heart of {location}.")
    print(f"The store was filled with the usual goods: {thingOne}, {thingTwo}, and everything in between.")
    print("")
    print(f"Suddenly, {soundEffect.upper()}!!! The ground began to shake!")
    print("")
    print(f"A DRAGON?! and not just any dragon, but a {adjOne} dragon the size of a jeepney —")
    print(f"crashed through the roof of the sari-sari store! Its scales sparkled like {thingTwo} in the sun,")
    print(f"and its breath smelled strongly of {faveFood}.")
    print("")
    print(f"Before Aling {storeName} could even say \"{exclaim}!\"")
    print("the dragon opened its massive mouth and... GULP!")
    print(f"It swallowed Aling {storeName} whole!")
    print("")
    print(f"Inside the dragon's stomach, it was dark, warm, and surprisingly smelled like {thingOne}.")
    print(f"Aling {storeName} shouted, \"{exclaim}! Ang {adjTwo} ko naman!\"")
    print("")
    print("But then, the dragon made a funny face.")
    print(f"\"BLEGH!\" the dragon roared. \"TOO BITTER! This human tastes like {thingTwo} na sira!\"")
    print("")
    print(f"And with a powerful {soundEffect}, the dragon SPIT Aling {storeName} out!")
    print("")
    print("But wait... the dragon didn't leave. Instead, it pointed its claw at a nearby bahay kubo.")
    print(f"Suddenly, the small nipa hut began to glow with a {adjOne} light!")
    print("")
    print("\"Sakay na!\" the dragon said in perfect Tagalog.")
    print("")
    print(f"Aling {storeName} climbed onto the flying bahay kubo, and together they soared through the sky,")
    print(f"past the clouds of {location}, over the rice terraces, and into the stars!")
    print("")
    print(f"They flew for {num} days and {num} nights until they reached the edge of the universe.")
    print("")
    print(f"And there, floating on a cloud made of {thingOne} and starlight, was a COSMIC BEING!")
    print("")
    print(f"The Cosmic Being had {num} eyes, each one twinkling like a star,")
    print(f"and its body was made of pure {adjTwo} energy.")
    print("")
    print(f"\"{exclaim.upper()}!\" the Cosmic Being boomed, its voice echoing through space.")
    print("\"I have been waiting for someone who is brave enough to be eaten by a dragon,")
    print(f"bitter enough to be spit out, and {adjOne} enough to ride a flying bahay kubo!\"")
    print("")
    print(f"The Cosmic Being waved its {bodyPart}, and suddenly...")
    print("")
    print("POOF!")
    print("")
    print(f"Aling {storeName} woke up back in the sari-sari store,")
    print(f"with a {creature} buying {thingOne} at the counter.")
    print("")
    print(f"\"Ano ang gusto mo?\" Aling {storeName} asked, wondering if it was all a dream.")
    print("")
    print(f"The {creature} smiled mysteriously and whispered,")
    print("\"The cosmic being says... thank you for being bitter enough to save the universe.\"")
    print("")
    print("=" * 60)
    print("THE END... OR IS IT?")
    print("=" * 60)
    print("")
    print("items brought to you by:")
    print(f"Sari-sari Store Owner: Aling {storeName}")
    print(f"Dragon's Favorite Snack: {faveFood}")
    print(f"Flying Bahay Kubo Destination: {location}")
    print(f"Mysterious Customer: The {creature}")
    print("")
    print("=" * 60)
    
    # made a loop for playing again or not
    again = input("\nGusto mo pa? Want to play again? (yes/no): ")
    if again.lower() == 'yes':
        print("\n" + "-" * 40)
        print("Let's do this ooone more time.")
        print("-" * 40 + "\n")
        madlibs()  # restart the game
    else:
        print("\nThanks for playing!")

# run it
madlibs()